--
-- Netezza SQL 01 – create table as select * from ...
--
CREATE TABLE "DB4157_XX"."U4157_XX"."CUSTOMER" as SELECT * FROM "DB4157"."ADMIN"."CUSTOMER";
CREATE TABLE "DB4157_XX"."U4157_XX"."LINEITEM" as SELECT * FROM "DB4157"."ADMIN"."LINEITEM";
CREATE TABLE "DB4157_XX"."U4157_XX"."NATION" as SELECT * FROM "DB4157"."ADMIN"."NATION";
CREATE TABLE "DB4157_XX"."U4157_XX"."ORDERS" as SELECT * FROM "DB4157"."ADMIN"."ORDERS";
CREATE TABLE "DB4157_XX"."U4157_XX"."PART"  as SELECT * FROM "DB4157"."ADMIN"."PART";
CREATE TABLE "DB4157_XX"."U4157_XX"."PARTSUPP" as SELECT * FROM "DB4157"."ADMIN"."PARTSUPP";
CREATE TABLE "DB4157_XX"."U4157_XX"."REGION" as SELECT * FROM "DB4157"."ADMIN"."REGION";
CREATE TABLE "DB4157_XX"."U4157_XX"."SUPPLIER" as SELECT * FROM "DB4157"."ADMIN"."SUPPLIER";

--
-- Netezza SQL 02 - number of years of data 
--                  in the LINEITEM and ORDERS tables 
--
SELECT DISTINCT DATE_PART('YEAR', "L_RECEIPTDATE")
from "DB4157_XX"."U4157_XX"."LINEITEM" ORDER BY 1;

SELECT DISTINCT DATE_PART('YEAR', "O_ORDERDATE")
from "DB4157_XX"."U4157_XX"."ORDERS" ORDER BY 1;

--
-- Netezza SQL 03 - archive data for the years 
--                  2016 to 2019 into a Netezza archive table
--
CREATE TABLE "DB4157_XX"."U4157_XX"."LINEITEM_ARCHIVE" as 
SELECT * FROM "DB4157_XX"."U4157_XX"."LINEITEM" 
WHERE DATE_PART('YEAR', "L_RECEIPTDATE") < 2020;

CREATE TABLE "DB4157_XX"."U4157_XX"."ORDERS_ARCHIVE" as 
SELECT * FROM "DB4157_XX"."U4157_XX"."ORDERS" 
WHERE DATE_PART('YEAR', "O_ORDERDATE") < 2020;

--
-- Netezza SQL 04 - delete the history records from LINEITEM and ORDERS
--
DELETE FROM "DB4157_XX"."U4157_XX"."LINEITEM" 
WHERE DATE_PART('YEAR', "L_RECEIPTDATE") < 2020;

DELETE FROM "DB4157_XX"."U4157_XX"."ORDERS"
WHERE DATE_PART('YEAR', "O_ORDERDATE") < 2020;

--
-- Netezza SQL 05 – Check base tables dates from 2020 to 2022 for LINEITEM and ORDERS
--
SELECT DISTINCT DATE_PART('YEAR', "L_RECEIPTDATE")
from "DB4157_XX"."U4157_XX"."LINEITEM" ORDER BY 1;

SELECT DISTINCT DATE_PART('YEAR', "O_ORDERDATE")
from "DB4157_XX"."U4157_XX"."ORDERS" ORDER BY 1;

--
-- Netezza SQL 06 – Check temporary archive tables dates from 2016 to 2019 for LINEITEM and ORDERS
--
SELECT DISTINCT DATE_PART('YEAR', "L_RECEIPTDATE")
from "DB4157_XX"."U4157_XX"."LINEITEM_ARCHIVE" ORDER BY 1;

SELECT DISTINCT DATE_PART('YEAR', "O_ORDERDATE")
from "DB4157_XX"."U4157_XX"."ORDERS_ARCHIVE" ORDER BY 1;

--
-- Netezza/Iceberg Query 07 – select data from an iceberg table
--
SELECT
  *
FROM
  "WXD_ICEBERG_4157"."U4157_WXDSHARE"."LINEITEM_HISTORY"
LIMIT
  10;

--
-- Netezza/Iceberg Query 08 – join from Netezza and watsonx.data/iceberg table
--
SELECT
  (
    SELECT
      COUNT(*)
    FROM "WXD_ICEBERG_4157"."U4157_WXDSHARE"."LINEITEM_HISTORY" -- watsonx.data table
  ) + (
    SELECT
      COUNT(*)
    FROM
      "DB4157_SHARE"."U4157_SHARE"."LINEITEM" -- local Netezza table
  ) AS total_count
;  

