--
-- Db2 Warehouse SQL 01 – create table as select * from ...
--
CREATE TABLE "U4157_XX"."CUSTOMER" as (SELECT * FROM "U4157"."CUSTOMER") with data in OBJSTORESPACE1;
CREATE TABLE "U4157_XX"."LINEITEM" as (SELECT * FROM "U4157"."LINEITEM") with data in OBJSTORESPACE1;
CREATE TABLE "U4157_XX"."NATION"   as (SELECT * FROM "U4157"."NATION")   with data in OBJSTORESPACE1;
CREATE TABLE "U4157_XX"."ORDERS"   as (SELECT * FROM "U4157"."ORDERS")   with data in OBJSTORESPACE1;
CREATE TABLE "U4157_XX"."PART"     as (SELECT * FROM "U4157"."PART")     with data in OBJSTORESPACE1;
CREATE TABLE "U4157_XX"."PARTSUPP" as (SELECT * FROM "U4157"."PARTSUPP") with data in OBJSTORESPACE1;
CREATE TABLE "U4157_XX"."REGION"   as (SELECT * FROM "U4157"."REGION")   with data in OBJSTORESPACE1;
CREATE TABLE "U4157_XX"."SUPPLIER" as (SELECT * FROM "U4157"."SUPPLIER") with data in OBJSTORESPACE1;

--
-- Db2 Warehouse SQL 02 - number of years of data 
--                  in the LINEITEM and ORDERS tables 
--
SELECT DISTINCT DATE_PART('YEAR', "L_RECEIPTDATE")
from "U4157_XX"."LINEITEM" ORDER BY 1;

SELECT DISTINCT DATE_PART('YEAR', "O_ORDERDATE")
from "U4157_XX"."ORDERS" ORDER BY 1;

--
-- Db2 Warehouse SQL 03 - archive data for the years 
--                        2016 to 2019 into a Netezza archive table
--
CREATE TABLE "U4157_XX"."LINEITEM_ARCHIVE" as 
(SELECT * FROM "U4157_XX"."LINEITEM" WHERE DATE_PART('YEAR', "L_RECEIPTDATE") < 2020) 
with data in OBJSTORESPACE1;

CREATE TABLE "U4157_XX"."ORDERS_ARCHIVE" as 
(SELECT * FROM "U4157_XX"."ORDERS" WHERE DATE_PART('YEAR', "O_ORDERDATE") < 2020) 
with data in OBJSTORESPACE1;
--
-- Db2 Warehouse SQL 04 - delete the history records from LINEITEM and ORDERS
--
DELETE FROM "U4157_XX"."LINEITEM" WHERE YEAR(L_RECEIPTDATE) < 2020;
DELETE FROM "U4157_XX"."ORDERS" WHERE YEAR(O_ORDERDATE) < 2020;

--
-- Db2 Warehouse SQL 05 – Check base tables dates from 2020 to 2022 for LINEITEM and ORDERS
--
SELECT DISTINCT DATE_PART('YEAR', "L_RECEIPTDATE")
from "U4157_XX"."LINEITEM" ORDER BY 1;

SELECT DISTINCT DATE_PART('YEAR', "O_ORDERDATE")
from "U4157_XX"."ORDERS" ORDER BY 1;

--
-- Db2 Warehouse SQL 06 – Check temporary archive tables dates from 2016 to 2019 for LINEITEM and ORDERS
--
SELECT DISTINCT DATE_PART('YEAR', "L_RECEIPTDATE")
from "U4157_XX"."LINEITEM_ARCHIVE" ORDER BY 1;

SELECT DISTINCT DATE_PART('YEAR', "O_ORDERDATE")
from "U4157_XX"."ORDERS_ARCHIVE" ORDER BY 1;
